# Netlify deployment configuration
# This file helps configure your Netlify deployment

# Build settings
[build]
  command = "npm run build"
  publish = "dist"
  
# Environment variables for production
# Note: You'll need to set these in your Netlify dashboard
[build.environment]
  # These are examples - replace with your actual backend URLs
  # VITE_API_BASE_URL = "https://your-backend-domain.com/api"
  # VITE_FRONTEND_URL = "https://your-netlify-app.netlify.app"

# Redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https: wss:;"